#!/bin/bash
# Resolves root directory safely
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT_DIR="$(dirname "$(dirname "$SCRIPT_DIR")")"
cd "$ROOT_DIR"

echo "🤖 Starting AI Session in $ROOT_DIR"
echo "   - Updating timestamp in CURRENT_FOCUS.md"
sed -i.bak "s/Last updated:.*/Last updated: $(date +%Y-%m-%d)/" .ai/context/CURRENT_FOCUS.md
echo "✅ Context refreshed."
echo ""
echo "🚀 To load this context into your AI assistant, use one of the following:"
echo ""
echo "   [Claude Code]"
echo "   claude-code .ai/context/*.md"
echo ""
echo "   [Aider]"
echo "   aider --read .ai/context/PROJECT_OVERVIEW.md --read .ai/context/CURRENT_FOCUS.md --read .ai/context/ARCHITECTURE.md"
echo ""
echo "   [Cursor]"
echo "   (Context is automatically loaded via .cursor/rules.md)"
echo ""
echo "   [Manual Copy/Paste]"
echo "   cat .ai/context/*.md | pbcopy  # (or clip.exe on WSL)"
echo ""
